// Code generated by Kitex v0.3.4. DO NOT EDIT.

package kanbandatabase

import (
	"context"
	"github.com/MonteCarloClub/KBD/kitex_gen/api"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return kanBanDatabaseServiceInfo
}

var kanBanDatabaseServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "kanBanDatabase"
	handlerType := (*api.KanBanDatabase)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetData":        kitex.NewMethodInfo(getDataHandler, newKanBanDatabaseGetDataArgs, newKanBanDatabaseGetDataResult, false),
		"PutData":        kitex.NewMethodInfo(putDataHandler, newKanBanDatabasePutDataArgs, newKanBanDatabasePutDataResult, false),
		"GetAccountData": kitex.NewMethodInfo(getAccountDataHandler, newKanBanDatabaseGetAccountDataArgs, newKanBanDatabaseGetAccountDataResult, false),
		"SetAccountData": kitex.NewMethodInfo(setAccountDataHandler, newKanBanDatabaseSetAccountDataArgs, newKanBanDatabaseSetAccountDataResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.4",
		Extra:           extra,
	}
	return svcInfo
}

func getDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.KanBanDatabaseGetDataArgs)
	realResult := result.(*api.KanBanDatabaseGetDataResult)
	success, err := handler.(api.KanBanDatabase).GetData(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKanBanDatabaseGetDataArgs() interface{} {
	return api.NewKanBanDatabaseGetDataArgs()
}

func newKanBanDatabaseGetDataResult() interface{} {
	return api.NewKanBanDatabaseGetDataResult()
}

func putDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.KanBanDatabasePutDataArgs)
	realResult := result.(*api.KanBanDatabasePutDataResult)
	success, err := handler.(api.KanBanDatabase).PutData(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKanBanDatabasePutDataArgs() interface{} {
	return api.NewKanBanDatabasePutDataArgs()
}

func newKanBanDatabasePutDataResult() interface{} {
	return api.NewKanBanDatabasePutDataResult()
}

func getAccountDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.KanBanDatabaseGetAccountDataArgs)
	realResult := result.(*api.KanBanDatabaseGetAccountDataResult)
	success, err := handler.(api.KanBanDatabase).GetAccountData(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKanBanDatabaseGetAccountDataArgs() interface{} {
	return api.NewKanBanDatabaseGetAccountDataArgs()
}

func newKanBanDatabaseGetAccountDataResult() interface{} {
	return api.NewKanBanDatabaseGetAccountDataResult()
}

func setAccountDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.KanBanDatabaseSetAccountDataArgs)
	realResult := result.(*api.KanBanDatabaseSetAccountDataResult)
	success, err := handler.(api.KanBanDatabase).SetAccountData(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKanBanDatabaseSetAccountDataArgs() interface{} {
	return api.NewKanBanDatabaseSetAccountDataArgs()
}

func newKanBanDatabaseSetAccountDataResult() interface{} {
	return api.NewKanBanDatabaseSetAccountDataResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetData(ctx context.Context, req *api.GetDataRequest) (r *api.GetDataResponse, err error) {
	var _args api.KanBanDatabaseGetDataArgs
	_args.Req = req
	var _result api.KanBanDatabaseGetDataResult
	if err = p.c.Call(ctx, "GetData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PutData(ctx context.Context, req *api.PutDataRequest) (r *api.PutDataResponse, err error) {
	var _args api.KanBanDatabasePutDataArgs
	_args.Req = req
	var _result api.KanBanDatabasePutDataResult
	if err = p.c.Call(ctx, "PutData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAccountData(ctx context.Context, req *api.GetAccountDataRequest) (r *api.GetAccountDataResponse, err error) {
	var _args api.KanBanDatabaseGetAccountDataArgs
	_args.Req = req
	var _result api.KanBanDatabaseGetAccountDataResult
	if err = p.c.Call(ctx, "GetAccountData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAccountData(ctx context.Context, req *api.SetAccountDataRequest) (r *api.SetAccountDataResponse, err error) {
	var _args api.KanBanDatabaseSetAccountDataArgs
	_args.Req = req
	var _result api.KanBanDatabaseSetAccountDataResult
	if err = p.c.Call(ctx, "SetAccountData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
